export const languages = [
  { name: "C", attribute: "c" },
  { name: "C++", attribute: "cpp" },
  { name: "C#", attribute: "csharp" },
  { name: "Java", attribute: "java" },
  { name: "Python", attribute: "python" },
  { name: "JavaScript", attribute: "javascript" },
  { name: "TypeScript", attribute: "typescript" },
  { name: "HTML", attribute: "html" },
  { name: "CSS", attribute: "css" },
  { name: "PHP", attribute: "php" },
  { name: "Ruby", attribute: "ruby" },
  { name: "Swift", attribute: "swift" },
  { name: "Go", attribute: "go" },
  { name: "Rust", attribute: "rust" },
  { name: "Kotlin", attribute: "kotlin" },
  { name: "MATLAB", attribute: "matlab" },
  { name: "Bash", attribute: "bash" },
  { name: "PowerShell", attribute: "powershell" },
];
