export const Languages = [
  { name: "Plain Text", value: "plaintext" },

  { name: "JavaScript", value: "javascript" },
  { name: "HTML", value: "html" },
  { name: "CSS", value: "css" },
  { name: "TypeScript", value: "typescript" },
  { name: "Python", value: "python" },
  { name: "XML", value: "xml" },
  { name: "ABAP", value: "abap" },
  { name: "Apex", value: "apex" },
  { name: "Azure CLI", value: "azcli" },
  { name: "Batch File", value: "bat" },
  { name: "Bicep", value: "bicep" },
  { name: "Cameligo", value: "cameligo" },
  { name: "Clojure", value: "clojure" },
  { name: "CoffeeScript", value: "coffeescript" },
  { name: "C", value: "c" },
  { name: "C++", value: "cpp" },
  { name: "C#", value: "csharp" },
  { name: "Content Security Policy", value: "csp" },
  { name: "Cypher", value: "cypher" },
  { name: "Dart", value: "dart" },
  { name: "Dockerfile", value: "dockerfile" },
  { name: "ECL", value: "ecl" },
  { name: "Elixir", value: "elixir" },
  { name: "Flow9", value: "flow9" },
  { name: "F#", value: "fsharp" },
  { name: "Go", value: "go" },
  { name: "GraphQL", value: "graphql" },
  { name: "Handlebars", value: "handlebars" },
  { name: "HCL", value: "hcl" },
  { name: "INI", value: "ini" },
  { name: "Java", value: "java" },
  { name: "Julia", value: "julia" },
  { name: "Kotlin", value: "kotlin" },
  { name: "LESS", value: "less" },
  { name: "Lexon", value: "lexon" },
  { name: "Lua", value: "lua" },
  { name: "M3", value: "m3" },
  { name: "Markdown", value: "markdown" },
  { name: "MDX", value: "mdx" },
  { name: "MISP", value: "misp" },
  { name: "MSDAX", value: "msdax" },
  { name: "MySQL", value: "mysql" },
  { name: "Objective-C", value: "objective-c" },
  { name: "Pascal", value: "pascal" },
  { name: "Pascaligo", value: "pascaligo" },
  { name: "Perl", value: "perl" },
  { name: "Postiats", value: "postiats" },
  { name: "Power Query", value: "powerquery" },
  { name: "PowerShell", value: "powershell" },
  { name: "Protocol Buffers", value: "proto" },
  { name: "Python", value: "python" },
  { name: "Q#", value: "qsharp" },
  { name: "R", value: "r" },
  { name: "Razor", value: "razor" },
  { name: "Redis", value: "redis" },
  { name: "Redshift", value: "redshift" },
  { name: "reStructuredText", value: "restructuredtext" },
  { name: "Ruby", value: "ruby" },
  { name: "Rust", value: "rust" },
  { name: "SB", value: "sb" },
  { name: "Scala", value: "scala" },
  { name: "Scheme", value: "scheme" },
  { name: "SCSS", value: "scss" },
  { name: "Shell", value: "shell" },
  { name: "Solidity", value: "sol" },
  { name: "AES", value: "aes" },
  { name: "SparkQL", value: "sparkql" },
  { name: "SQL", value: "sql" },
  { name: "ST", value: "st" },
  { name: "Swift", value: "swift" },
  { name: "SystemVerilog", value: "systemverilog" },
  { name: "Verilog", value: "verilog" },
  { name: "Tcl", value: "tcl" },
  { name: "Twig", value: "twig" },
  { name: "VB", value: "vb" },
  { name: "WebGPU Shader Language", value: "wgsl" },
  { name: "XML", value: "xml" },
  { name: "YAML", value: "yaml" },
  { name: "JSON", value: "json" },
];
